project:
  type: website
  render:
    - 00-intro.qmd
    - 00-intro.es.qmd
    - 01-cleaning/01-cleaning-01-checks.qmd
    - 01-cleaning/01-cleaning-01-checks.qmd
    - 01-cleaning/01-cleaning-02-add-duration-others.qmd
    - 01-cleaning/01-cleaning-02-add-duration-others.es.qmd
    - 01-cleaning/01-cleaning-03-logical-with-lists.qmd
    - 01-cleaning/01-cleaning-03-logical-with-lists.es.qmd
    - 01-cleaning/01-cleaning-04-practice.qmd
    - 01-cleaning/01-cleaning-04-practice.es.qmd
    - 02-cleaning/02-cleaning-01-create-cleaning-log.qmd
    - 02-cleaning/02-cleaning-01-create-cleaning-log.es.qmd
    - 02-cleaning/02-cleaning-02-create-clean-dataset.qmd
    - 02-cleaning/02-cleaning-02-create-clean-dataset.es.qmd
    - 02-cleaning/02-cleaning-03-review-cleaning.qmd
    - 02-cleaning/02-cleaning-03-review-cleaning.es.qmd
    - 02-cleaning/02-cleaning-04-practice.qmd
    - 02-cleaning/02-cleaning-04-practice.es.qmd
    - 02-cleaning/02-cleaning-05-extra.qmd
    - 02-cleaning/02-cleaning-05-extra.es.qmd
    - 03-composition/03-composition-01-add.qmd
    - 03-composition/03-composition-01-add.es.qmd
    - 03-composition/03-composition-02-review.qmd
    - 03-composition/03-composition-02-review.es.qmd
    - 03-composition/03-composition-03-practice.qmd
    - 03-composition/03-composition-03-practice.es.qmd
    - 03-composition/03-composition-04-extra.qmd
    - 03-composition/03-composition-04-extra.es.qmd
website:
  title: "Intoduction to R framework at IMPACT Initiatives"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Introduction"
        href: 00-intro.qmd
      - section: "Cleaning - Checking a dataset"
        contents:
          - 01-cleaning/01-cleaning-01-checks.qmd
          - 01-cleaning/01-cleaning-02-add-duration-others.qmd
          - 01-cleaning/01-cleaning-03-logical-with-lists.qmd
          - 01-cleaning/01-cleaning-04-practice.qmd
      - section: "Cleaning - Creating a clean dataset"
        contents:
          - 02-cleaning/02-cleaning-01-create-cleaning-log.qmd
          - 02-cleaning/02-cleaning-02-create-clean-dataset.qmd
          - 02-cleaning/02-cleaning-03-review-cleaning.qmd
          - 02-cleaning/02-cleaning-04-practice.qmd
          - 02-cleaning/02-cleaning-05-extra.qmd
      - section: "Composition - Add indicators"
        contents:
          - 03-composition/03-composition-01-add.qmd
          - 03-composition/03-composition-02-review.qmd
          - 03-composition/03-composition-03-practice.qmd
          - 03-composition/03-composition-04-extra.qmd
  repo-url: https://github.com/impact-initiatives/R-framework-with-IMPACT---how-to-use-the-tools
  repo-actions: [edit, source, issue]
format:
  html:
    toc: true
    code-link: true
    theme:
      - simplex
      - config/custom.scss
    df-print: kable
    embed-resources: true

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: es
    text: "Español"
  - name: fr
    text: "Francais"
  - name: en
    text: "Anglais"
  mainlanguage: 'en'
  languages: ['es', 'fr']
title-es: Introduction au cadre R chez IMPACT Initiatives
title-fr: Intoducciòn al Marco R en IMPACT Initiatives
description-es: description in es
description-fr: description in fr
author-es: author in es
author-fr: author in fr
lang: en
