project:
  type: website
  render:
      - 01-session1.qmd
      - 01-session1.es.qmd
      - 02-session2.qmd
      - 02-session2.es.qmd
      - 03-session3.qmd
      - 03-session3.es.qmd
      - 04-session4.qmd
      - 04-session4.es.qmd

website:
  title: "Intoduction to R framework at IMPACT Initiatives"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "session 1"
        href: 01-session1.qmd
      - text: "session 2"
        href: 02-session2.qmd
      - text: "session 3"
        href: 03-session2.qmd
      - text: "session 4"
        href: 04-session4.qmd
format:
  html:
    toc: true
    code-link: true
    theme:
      - simplex
      - config/custom.scss
    df-print: kable
    embed-resources: true


babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: es
    text: "Español"
  - name: fr
    text: "Francais"
  - name: en
    text: "Anglais"
  mainlanguage: 'en'
  languages: ['es', 'fr']
title-es: Introduction au cadre R chez IMPACT Initiatives
title-fr: Intoducciòn al Marco R en IMPACT Initiatives
description-es: description in es
description-fr: description in fr
author-es: author in es
author-fr: author in fr
lang: en
